### ISSUE TITLE
Search: commit message: Undefined array key "stf_message" in /usr/local/www/freshports/classes/commit_ports.php on line 96

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#431] opened 2023-02-16 06:46 UTC
For example, **commit message** contains _5.26_: 

<https://www.freshports.org/search.php?stype=commitmessage&method=match&query=5.26&num=50&orderby=category&orderbyupdown=asc&search=Search&format=html&branch=head>

* at a glance, the list of ports is preceded by a large number of warnings. 

Seeking a much more obscure phrase – _blah_ – the result is easier to dissect: 

<https://www.freshports.org/search.php?stype=commitmessage&method=match&query=blah&num=50&orderby=category&orderbyupdown=asc&search=Search&format=html&branch=head>

* two warnings

> Number of commits: 75 (showing only 50 on this page) 1  |  [2]

* page one lists only two ports.

**Comment by dlangille** [comment] 2023-02-16 13:39
This is most certainly an out-of-date SQL query not providing the `stf_message` field (Sanity Test Failure).

**Comment by dlangille** [comment] 2023-02-16 13:47
Problem can be reproduced on `dev`

**Comment by dlangille** [comment] 2023-02-16 14:13
Fixed on `dev` via:

```
[dev-nginx01 dan ~/www] % git diff --ignore-all-space classes/commits_by_description.php
diff --git a/classes/commits_by_description.php b/classes/commits_by_description.php
index 61fa5eee..20c590d0 100644
--- a/classes/commits_by_description.php
+++ b/classes/commits_by_description.php
@@ -53,7 +53,8 @@ class CommitsByDescription extends commits {
                        ports.expiration_date                                                                                        AS expiration_date,
                        date_part('epoch', ports.date_added)                                                                         AS date_added,
                        ports.element_id                                                                                             AS element_id,
-                       ports.short_description                                                                                     AS short_description";
+                       ports.short_description                                                                                      AS short_description,
+                       null                                                                                                         AS stf_message";
                if ($this->UserID) {
                                $sql .= ",
                        onwatchlist ";
[dev-nginx01 dan ~/www] % 
```

**Comment by dlangille** [comment] 2023-02-16 14:13
@grahamperrin  please validate.

**Comment by grahamperrin** [comment] 2023-02-16 20:04
I progressed from <https://dev.freshports.org/search.php?stype=commitmessage&method=match&query=5.26&num=50&orderby=category&orderbyupdown=asc&search=Search&format=html&branch=head> (at 19:42 UK time) to <https://dev.freshports.org/search.php?stype=commitmessage&method=match&query=blah&num=50&orderby=category&orderbyupdown=asc&search=Search&format=html&branch=head> (around 19:43) by manually changing the URL (_blah_ instead of _5.26_). 

☑ The result was **free from the originally reported warning**: 

> Undefined array key "stf_message" in /usr/local/www/freshports/classes/commit_ports.php on line 96

![image](https://user-images.githubusercontent.com/192271/219471292-dd01d856-0487-46d5-bfbb-de4daba15f34.png)

There was, however, a different warning, higher up the page: 

> Undefined variable $result in /usr/local/www/freshports/www/search.php on line 903

– and the number of commits is somehow wrong (75 counted, only **three** listed). 

I manually edited the URL to <https://dev.freshports.org/search.php>, visited the address, pulled the menu down to _Commit Message_, entered the same search phrase _blah_, keyed return and got **more than three** listed. 

Also remarkable (I forgot to mention this at the outset): RIP gravestones amongst the results, whilst **☐ Include deleted ports** is _not_ checked. 

----

Sorry, that's quite a mash, I guess that at least one aspect should be spun off to a separate issue.

**Comment by dlangille** [comment] 2023-02-16 20:11
> Undefined variable $result in /usr/local/www/freshports/www/search.php on line 903

I noticed: that appears only if not logged in.

**Comment by dlangille** [comment] 2023-02-16 20:22
> > Undefined variable $result in /usr/local/www/freshports/www/search.php on line 903
> 
> I noticed: that appears only if not logged in.

That problem fix by this diff:

```
@@ -646,7 +652,13 @@
                    $Commits->SetLimit($PageSize);
 
                    $NumFetches = $Commits->Fetch();
-#                  $result     = $Commits->LocalResult;
+                   $result     = $Commits->LocalResult;
+                   if ($Debug) {
+                       if ($result) {
+                               echo "
+<br>we have a result for SEARCH_FIELD_COMMITMESSAGE<br>\n";
+                       }
+                   }
                    break;
 
                  case SEARCH_FIELD_PATHNAME:
```

**Comment by dlangille** [comment] 2023-02-16 20:29
I think this remains:

* last page of the results
* says "Number of commits: 128 (showing only 8 on this page)"
* only 5 showing on this page
* https://dev.freshports.org/search.php?stype=commitmessage&method=match&query=5.26&num=30&orderby=category&orderbyupdown=asc&search=Search&format=html&branch=head&page=5


It might be the same reason why this one shows:

* Number of commits: 75 (showing only 50 on this page) 1
* only 2 showing (3 if not logged in)
* https://dev.freshports.org/search.php?stype=commitmessage&method=match&query=blah&num=50&orderby=category&orderbyupdown=asc&search=Search&format=html&branch=head

**Comment by dlangille** [comment] 2023-03-17 10:54
Testing the second URL in the above comment:

Logged in:

* search limited to 10 or 20 - nothing returned
* search limited to 30 - 75 results


NOTE: the results include deleted ports when 'Include deleted ports' is not checked - I'll say this is correct because you searching commit messages, not ports.

**Comment by dlangille** [comment] 2023-03-17 11:09
This is an SQL problem.

Starting with the basics:

```
SELECT * FROM commit_log CL WHERE 
     CL.description ILIKE '%blah%'
```

That finds 75 commits.

**Comment by dlangille** [comment] 2023-03-17 11:24
With that change, we get 29 results.

NOTE: the page says `29 commits` - really, it's 29 ports.

**Comment by dlangille** [comment] 2023-03-17 11:40
@grahamperrin I now think the count and number of ports displayed should match.

The results say 'commits', it should say 'ports'.

The next decision: if we are searching commit messages, do we show ports in the results? We could show commits, then you click on the commit to see the ports (if any) affected by that commit.  This would make it easier to also include `src` commits, if that option is selected.

**Closed** 2023-03-26 23:10 UTC
Labels: bug
