### ISSUE TITLE
no Conflicts Matches for this port - accurate or not?

### ISSUE THREAD

**Issue by Tectu** [FreshPorts/freshports#566] opened 2024-06-01 17:45 UTC
While looking at [`www/onlyoffice-documentserver`](https://www.freshports.org/www/onlyoffice-documentserver/#conflicts) I came across this:

> Conflicts Matches:
>       There are no Conflicts Matches for this port. This is usually an error.

That seems fishy.

See also #567

**Comment by dlangille** [comment] 2024-06-19 14:06
Oddly, as I look at this today, I cannot recall what `Conflicts Matches` are... I'll have to read the code.

The table is empty:

```
freshports.dvl=# select count(*) from ports_conflicts_matches;
 count 
-------
     0
(1 row)
```

There is nothing in the ingress code:

```
[14:05 dvl-ingress01 dvl ~/scripts] % grep -r ports_conflicts_matches *
[14:05 dvl-ingress01 dvl ~/scripts] % cd ~/modules 
[14:05 dvl-ingress01 dvl ~/modules] % grep -r ports_conflicts_matches *
grep: config.pm: Permission denied
[14:05 dvl-ingress01 dvl ~/modules] % 
```

I found nothing in stored procedures or relation integrity.

**Comment by dlangille** [comment] 2024-06-19 14:14
The blog contains references, and the second one seems to be most relevant.

* https://news.freshports.org/2018/10/06/getting-a-link-from-a-package-name/
* https://news.freshports.org/2018/09/26/adding-and-populating-conflicts/

From the second post, we have [this gist](https://gist.github.com/dlangille/65fdf259d7dddf70d040f366c825bbb3), which explains how to populate the table.

Ahh, the bottom of the article mentions `Future work` and how to populate the table:

The next job is to automatically populate the ports_conflicts_matches table. I think that needs to be done on a periodic basis, perhaps every 10 minutes if there has been a recent commit.

Just thinking about that now:

1. If port A conflicts with port B, then clearly port B conflicts with port A. I am not sure if there is a requirement to specify CONFLICTS in both ports, but that is something easily confirmed by the ports_conlicts table.
2. I tried to think of commits which would not change ports_conflicts_matches. Since the matches can include PORTVERSION, any given commit which bumps that value can affect matches.
3. Perhaps I could exclude commits to UPDATING, MOVED, or Mk, but they are relatively few compared to the rest.
4. I think it’s just safer to recompute all matches periodically. There does not seem to be a safe and straight forward way to do it based upon a smaller unit of work.

**Comment by dlangille** [comment] 2024-06-19 14:22
This has been merged to the main branch - it will be on `dev` for a while, and will reach production with the next release.

**Closed** 2024-06-19 14:21 UTC
Labels: conflicts

**Comment by dlangille** [comment] 2024-10-13 16:37
Seems fixed to me.

![Screen Shot 2024-10-13 at 12 36 23 PM](https://github.com/user-attachments/assets/6e8f3d5d-f761-4e7c-ac21-4fb248cb6a8f)
