### ISSUE TITLE
Package sets are not being refreshed

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#276] opened 2021-05-16 08:58 UTC
For example: 

```text
% pkg rquery '%o %v %R' kde5
x11/kde5 5.21.5.21.04.0 FreeBSD
% grep url /etc/pkg/FreeBSD.conf 
  url: "pkg+http://pkg.FreeBSD.org/${ABI}/latest",
% uname -K
1400013
% 
```

* a package for `x11/kde5` is found.

In contrast, https://www.freshports.org/x11/kde5/#packages 

* nothing under _latest_ at the time of writing. 

A few days ago in IRC, @tcberner observed: 

> … an issue with freshports not updating its index on meta-ports

Please, can there be a methodical way to avoid this issue?

**Comment by grahamperrin** [comment] 2021-05-16 09:06
Ah: 

☑ https://devgit.freshports.org/x11/kde5/#packages `5.21.5.21.04.0` FreeBSD:14:amd64 latest

☑ https://stage.freshports.org/x11/kde5/#packages `5.21.5.21.04.0` FreeBSD:14:amd64 latest

☐ https://testgit.freshports.org/x11/kde5/#packages `5.20.5.20.12.2` FreeBSD:14:amd64 latest

**Comment by grahamperrin** [comment] 2021-05-16 09:25
Is https://git.langille.org/FreshPorts/packages-import still relevant? 

> Code for importing `packagesite.yaml` information …

**Comment by dlangille** [comment] 2021-05-16 13:19
I think you're saying prod is not keeping up to date with package information for x11/kde5

**Comment by dlangille** [comment] 2021-05-16 13:23
Mouse hover shows prod is checking for new packages.

![Screen Shot 2021-05-16 at 9 20 42 AM](https://user-images.githubusercontent.com/1626436/118398847-5a9b3400-b628-11eb-819a-d833deffcf52.png)

**Comment by dlangille** [comment] 2021-05-16 13:29
Whereas test has not looked since February.

![Screen Shot 2021-05-16 at 9 28 38 AM](https://user-images.githubusercontent.com/1626436/118399047-39871300-b629-11eb-9284-733d49e50b36.png)

**Comment by dlangille** [comment] 2021-05-16 13:31
stage is May 10th
![Screen Shot 2021-05-16 at 9 30 08 AM](https://user-images.githubusercontent.com/1626436/118399092-73581980-b629-11eb-9d12-a9271cf362be.png)

**Comment by dlangille** [comment] 2021-05-16 13:34
> Please, can there be a methodical way to avoid this issue?

I'm not sure what this means.

Do you mean for reporting that a webpage is not correct?

**Comment by dlangille** [comment] 2021-05-16 19:56
Current status:

* dev and prod match
* test and stage match

The two groups don't match each other.

**Comment by dlangille** [comment] 2021-05-16 20:01
Confirmed: `check_repos_for_new_stuff.py`is running hourly on all three hosts.

**Comment by dlangille** [comment] 2021-05-16 20:22
I have a theory about why test and stage are wrong.

Both site show `never imported` when you hover over [most of] the cells which contain a version.

I'll check the processing.

![Screen Shot 2021-05-16 at 4 19 51 PM](https://user-images.githubusercontent.com/1626436/118411458-b1256400-b662-11eb-9dd6-3b18f0312a61.png)

![Screen Shot 2021-05-16 at 4 19 40 PM](https://user-images.githubusercontent.com/1626436/118411459-b1bdfa80-b662-11eb-93aa-3e0b6393d405.png)

**Comment by dlangille** [comment] 2021-05-16 20:40
Now all of dev, test, stage, and production match.

test was wrong because there was a service caching issue.  Fixed with:

```
sudo service nginx stop
sudo zfs rollback nvd/freshports/testgit-nginx01/var/db/freshports/cache/categories@empty
sudo zfs destroy nvd/freshports/testgit-nginx01/var/db/freshports/cache/categories@empty
sudo rm -rf ~freshports/cache/packages/x11
sudo rm zfs snapshot nvd/freshports/testgit-nginx01/var/db/freshports/cache/categories@empty
sudo service nginx start
```

For some reason, that port (and perhaps only the `x11` category) was caught in the `snapshot`

**Comment by grahamperrin** [comment] 2021-05-17 01:16
Thanks for all of this. 

https://github.com/FreshPorts/freshports/issues/276#issuecomment-841817959

> I'm not sure what this means. …

In retrospect, maybe a different title would have been better. @dlangille feel free to edit. 

Background: someone in FreeBSD Forums couldn't find the package for kde5 (true at the time), [I responded](https://forums.FreeBSD.org/threads/freebsd-kommunity-edition.78594/post-511642) with reference to https://www.freshports.org/x11/kde5/#packages then had a very brief chat in `#kde-freebsd` in IRC, at which time an indexing issue was assumed.

**Comment by dlangille** [comment] 2021-05-17 01:36
I'll check these packages across all four host tomorrow.

**Comment by dlangille** [comment] 2021-05-21 15:36
> Now all of dev, test, stage, and production match.
> 
> test was wrong because there was a service caching issue. Fixed with:
> 
> ```
> sudo service nginx stop
> sudo zfs rollback nvd/freshports/testgit-nginx01/var/db/freshports/cache/categories@empty
> sudo zfs destroy nvd/freshports/testgit-nginx01/var/db/freshports/cache/categories@empty
> sudo rm -rf ~freshports/cache/packages/x11
> sudo rm zfs snapshot nvd/freshports/testgit-nginx01/var/db/freshports/cache/categories@empty
> sudo service nginx start
> ```
> 
> For some reason, that port (and perhaps only the `x11` category) was caught in the `snapshot`

After that `create`, I should have also done this:

`sudo zfs allow freshports rollback nvd/freshports/testgit-nginx01/var/db/freshports/cache/packages`

because:

```
May 21 15:00:37 testgit-nginx01 fp-listen[52103]: Time to rollback nvd/freshports/testgit-nginx01/var/db/freshports/cache/packages@empty
May 21 15:00:37 testgit-nginx01 fp_listen[52102]: cannot rollback 'nvd/freshports/testgit-nginx01/var/db/freshports/cache/packages': permission denied

```

**Comment by dlangille** [comment] 2021-05-24 21:28
This looks fine now.

**Closed by dlangille** 2021-05-24 21:28 UTC
