### ISSUE TITLE
Login/Cookie Expiration

### ISSUE THREAD

**Issue by nx6** [FreshPorts/freshports#574] opened 2024-06-19 23:28 UTC
OS: Windows 10 Pro, 22H2
Browser:  Firefox 127.0

If I have not visited the site in awhile and try to directly access the page for a port (or run a search, through a Firefox quick search trigger I have set up), I get sent to a blank page that says:

"Your user details were not found. You have been logged out. Please return to the [home page](https://www.freshports.org/)."

I didn't have this issue until I set up an account on FreshPorts (so I could start tracking ports and get notification emails). But creating an account has had the effect of lowering my experience instead.

It would be nice if my login wouldn't expire to quickly to begin with, but it would be better if the site handled this expiration more gracefully. If I'm just trying to view a port's page or run a search, the login status isn't really necessary, why not run return the requested page, but with the site in a logged out state, like most sites would in my experience?

**Comment by dlangille** [comment] 2024-06-20 11:18
At a minimum, I'll:

* change the message so it appears within the page you are viewing
* figure out why the cookie is expiring so quickly - I don't see any reason for it not to be multiple months.

**Comment by dlangille** [comment] 2024-06-22 13:41
`[Current code](https://github.com/FreshPorts/freshports/blob/2.9.2/www/login.php#L93)`:

```
'expires'  => time() + 60*60*24*120
```

That should work for 120 days (4 months). Seems long enough, especially if during each visit, the cookie time-to-live is refreshed (I need to confirm that refresh occurs).

**Comment by dlangille** [comment] 2024-06-22 13:44
In [classes/user.php](https://github.com/FreshPorts/freshports/blob/2.9.2/classes/user.php#L74), we have the `Your user details were not found` code. It reads from the `users` table matching up the `cookie` value: `SELECT users.* FROM users WHERE cookie = $1`

**Comment by dlangille** [comment] 2024-06-22 13:47
Oh wait. If you've visited the site from two different browsers, you'd have one cookie in one browser, and a different cookie in another. That might be what's messing this up.  I know, for me, that is a very likely scenario.

@nx6 is that a likely use case for you?

**Comment by dlangille** [comment] 2024-06-22 14:06
I have reproduced the issue by:

* logging into the website
* logging into the website via another browser (in my case, a private browsing session)
* reload the page from the first step

First impressions to allow multiple concurrent login sessions:

* each login generates the same cookie value (sounds bad to me)
* move the cookie value from the `users` table to another table, allowing for a `1:n` relationship

**Comment by dlangille** [comment] 2024-06-22 14:33
This might do:

```
freshports.dvl=# \d user_cookie
             Table "public.user_cookie"
 Column  |  Type   | Collation | Nullable | Default 
---------+---------+-----------+----------+---------
 user_id | integer |           | not null | 
 cookie  | text    |           | not null | 
Indexes:
    "user_cookie_pkey" PRIMARY KEY, btree (user_id, cookie)
Foreign-key constraints:
    "user_cookies_user_id" FOREIGN KEY (user_id) REFERENCES users(id)

freshports.dvl=# 
```

Question though: will the cookies per user be unique?

**Comment by dlangille** [comment] 2024-06-22 15:06
Yes, they should be [random enough](https://github.com/FreshPorts/freshports/blob/2.9.2/classes/user.php#L202C1-L205C1):

The cookie value is a hash of a unique id generated with a `random` number.

```
$token = hash('sha256', uniqid(random_int(0, getrandmax()), true));
```

**Comment by dlangille** [comment] 2024-06-22 15:10
Code to change:

* classes/user.php
* www/new-user.php
* www/logout.php
* www/customize.php
* www/bouncing.php
* www/delete-account.php

**Comment by nx6** [comment] 2024-06-22 18:38
If you've visited

@nx6 is that a likely use case for you?

> Oh wait. If you've visited the site from two different browsers, you'd have one cookie in one browser, and a different cookie in another. That might be what's messing this up. I know, for me, that is a very likely scenario.
> 
> @nx6 is that a likely use case for you?

Not different browsers really, but multiple machines (desktop and two laptops), so that is likely it.

**Comment by dlangille** [comment] 2024-06-22 21:23
Progress. I have login working on my offline dev host.

**Comment by dlangille** [comment] 2024-06-22 21:27
> > Oh wait. If you've visited the site from two different browsers, you'd have one cookie in one browser, and a different cookie in another. That might be what's messing this up. I know, for me, that is a very likely scenario.
> > @nx6 is that a likely use case for you?
> 
> Not different browsers really, but multiple machines (desktop and two laptops), so that is likely it.

Good to know. That means the cause of the problem is what I thought it was.  I'll continue with this work.

**Comment by dlangille** [comment] 2024-06-23 12:39
@nx6 this is now implemented at https://dev.freshports.org - but your account does not exist there. If you want to test this there, you'll need to create an account.

Still to do: I want to automatically extend the lifetime of the cookie each time it is used.  The initial life is 4 months; each time the cookie is used, that expiration time is reset to 4 months.

**Comment by dlangille** [comment] 2024-06-23 13:46
Done: cookie life extension.

**Comment by dlangille** [comment] 2024-06-23 14:53
dev.freshports.org now has a copy of production from about 0202 UTC on Jun 23 2024 - your production logins should work from there.

**Comment by dlangille** [comment] 2024-06-27 21:42
This fix has been merged to head and packaged. It is now available on `test`.

**Comment by dlangille** [comment] 2024-06-30 11:13
This is now in production.

What is not yet implemented - a better way of telling you: we don't have your login details - however, the frequency of such incidents should now be greatly reduced.

**Comment by dlangille** [comment] 2024-06-30 11:20
How often has that been happening lately? (These logs are rotated daily)

```
[11:18 aws-1-nginx01 dvl ~] % sudo grep -rc 'Could not find user details' /var/log/freshports/       
/var/log/freshports/freshports.log.1:0
/var/log/freshports/freshports.log.11:1
/var/log/freshports/freshports.log.6:3
/var/log/freshports/freshports.log.8:3
/var/log/freshports/freshports.log.2:2
/var/log/freshports/freshports.log.5:3
/var/log/freshports/freshports.log.12:1
/var/log/freshports/freshports.log.10:2
/var/log/freshports/freshports.log.7:2
/var/log/freshports/freshports.log.0:0
/var/log/freshports/freshports.log.4:7
/var/log/freshports/freshports.log.13:1
/var/log/freshports/freshports.log.3:6
/var/log/freshports/freshports.log.9:4
/var/log/freshports/freshports.log:2

**Comment by dlangille** [comment] 2024-06-30 11:22
Going to a snapshot for historical data:

```
[11:21 aws-1 dan /jails/nginx01/.zfs/snapshot/autosnap_2024-06-24_00:00:04_daily] % sudo grep -rc 'Could not find user details' var/log/freshports 
var/log/freshports/freshports.log.1:2
var/log/freshports/freshports.log.11:3
var/log/freshports/freshports.log.6:1
var/log/freshports/freshports.log.8:2
var/log/freshports/freshports.log.2:3
var/log/freshports/freshports.log.5:1
var/log/freshports/freshports.log.12:1
var/log/freshports/freshports.log.10:4
var/log/freshports/freshports.log.7:1
var/log/freshports/freshports.log.0:3
var/log/freshports/freshports.log.4:2
var/log/freshports/freshports.log.13:2
var/log/freshports/freshports.log.3:4
var/log/freshports/freshports.log.9:3
var/log/freshports/freshports.log:0

**Comment by dlangille** [comment] 2024-06-30 11:30
There, I think that should work better. Remove the `die`, keep the logging.

@nx6 OK to close?

**Comment by TimWolla** [comment] 2024-06-30 17:03
> Yes, they should be [random enough](https://github.com/FreshPorts/freshports/blob/2.9.2/classes/user.php#L202C1-L205C1):
> The cookie value is a hash of a unique id generated with a `random` number.

My understanding is that this is intended as some kind of session or login token. The code you linked is absolutely not random enough and does not generate a secure and unique user token. Please see: https://wiki.php.net/rfc/deprecations_php_8_4#deprecate_uniqid

I recommend `bin2hex(random_bytes(32))` to generate a secure 256-bit token (keeping the same format you currently use).

**Comment by dlangille** [comment] 2024-06-30 18:18
> I recommend `bin2hex(random_bytes(32))` to generate a secure 256-bit token (keeping the same format you currently use).

Good idea.  How about this:

```
[18:18 dvl-nginx01 dvl ~/www] % git diff            
diff --git a/classes/user.php b/classes/user.php
index 642d2b3d..782af238 100644
--- a/classes/user.php
+++ b/classes/user.php
@@ -200,7 +200,7 @@ class User {
        }
 
        function createUserToken() {
-               $token = hash('sha256', uniqid(random_int(0, getrandmax()), true));
+               $token = hash('sha256', bin2hex(random_bytes(32)));
                return $token;
        }
 
[18:17 dvl-nginx01 dvl ~/www] % 
```

**Comment by TimWolla** [comment] 2024-06-30 21:11
> How about this:

Use either:

```php
$token = bin2hex(random_bytes(32));
```

or

```php
$token = hash('sha256', random_bytes(32));
```

but combining bin2hex and SHA-256 doesn't make sense. Both options in this comment of mine are equivalent with regard to security (256 Bits of randomness). The first bin2hex-based one is probably a little faster.

**Comment by dlangille** [comment] 2024-06-30 21:37
I'm with it now.  I didn't realize that `keeping the same format` referred to 64 characters I was storing. 

Thank you.

```
[21:36 dvl-nginx01 dvl ~/www] % git diff            
diff --git a/classes/user.php b/classes/user.php
index 642d2b3d..89385136 100644
--- a/classes/user.php
+++ b/classes/user.php
@@ -200,7 +200,7 @@ class User {
        }
 
        function createUserToken() {
-               $token = hash('sha256', uniqid(random_int(0, getrandmax()), true));
+               $token = bin2hex(random_bytes(32));
                return $token;
        }
 
 
```

**Comment by dlangille** [comment] 2024-06-30 21:37
This will be in prod soon.

**Comment by dlangille** [comment] 2024-06-30 22:07
@TimWolla thank you for your help. This is now in production.

**Comment by nx6** [comment] 2024-07-01 04:02
> There, I think that should work better. Remove the `die`, keep the logging.
> 
> @nx6 OK to close?

Should be fine if you're all done. I really haven't been on enough to be able to judge things. Differentiating sessions between devices and the logout timeout being fixed should cover it.

**Closed** 2024-07-01 13:34 UTC
Labels: bug, enhancement
