### ISSUE TITLE
FreeBSD:15:aarch64 not showing up in the various "Packages (timestamps in pop-ups are UTC):" lists that I've just looked at

### ISSUE THREAD

**Issue by markmi** [FreshPorts/freshports#505] opened 2023-11-28 04:18 UTC
An example that I looked at is: https://www.freshports.org/devel/llvm17

It shows just the following for aarch64:
FreeBSD:12:aarch64
FreeBSD:13:aarch64
FreeBSD:14:aarch64

I will note that "FreeBSD:15:armv7" is shown.

**Comment by dlangille** [comment] 2023-12-07 00:57
Are we sure that FreeBSD:15:aarch64 exists?

**Comment by dlangille** [comment] 2023-12-07 01:15
I think this is the cause of the problem:

```freshports.dev=# select * from abi where name ilike '%aarch64' order by name;
 id |        name        | active 
----+--------------------+--------
  9 | FreeBSD:12:aarch64 | t
  2 | FreeBSD:13:aarch64 | t
 26 | FreeBSD:14:aarch64 | t
```

**Comment by markmi** [comment] 2023-12-07 01:18
See: https://pkg.freebsd.org/FreeBSD:15:aarch64/ and also: https://pkg.freebsd.org/FreeBSD:15:aarch64/latest/

It is also mentioned on: https://pkg.freebsd.org . The link there takes one to the first URL indicated above.

aarch64 is tier 1 for FreeBSD and has been since 13.0 . Tier 1 criteria make requirements in this area.

See: https://www.freebsd.org/platforms/  for the Tier level status.

FreeBSD:15:* (a.k.a main after 14 branched) does not have quarterly. The platforms with a sufficient tier do have latest.

**Comment by dlangille** [comment] 2023-12-07 01:20
Fixed on prod:

```
freshports.org=> begin;
BEGIN
freshports.org=> insert into abi (name) values ('FreeBSD:15:aarch64');
INSERT 0 1
freshports.org=> select * from abi where name ilike 'FreeBSD:15%' order by name;
 id |         name         | active 
----+----------------------+--------
 43 | FreeBSD:15:aarch64   | t
 36 | FreeBSD:15:amd64     | t
 37 | FreeBSD:15:armv6     | t
 38 | FreeBSD:15:armv7     | t
 39 | FreeBSD:15:i386      | t
 40 | FreeBSD:15:mips64    | t
 41 | FreeBSD:15:powerpc64 | t
 42 | FreeBSD:15:riscv64   | t
(8 rows)

freshports.org=> commit;
COMMIT
freshports.org=> 
```

The fix should be on the website by about 0205 UTC on 2023-12-07.

**Comment by markmi** [comment] 2023-12-07 01:45
Well, Technically FreeBSD:15:* have a projected Tier status listed on https://www.freebsd.org/platforms/ . But:

mips64 shows as unsupported at 14.x and later. mips64 is not listed at all on https://pkg.freebsd.org/

armv6 shows as unsupported at 15.x . https://pkg.freebsd.org/FreeBSD:15:armv6/ is empty.
NOTE: https://pkg.freebsd.org/FreeBSD:14:armv6/latest/ is back at 2023-Jan-15 and there is no quarterly/ .

For powerpc64le (not in your list):
https://www.freebsd.org/platforms/ lists it as tier 2 (like powerpc64) for 14.x and 15.x .
https://www.freebsd.org/platforms/ lists "FreeBSD:14:powerpc64le (only quarterly is updated)" (with a URL bound)
https://pkg.freebsd.org/FreeBSD:14:powerpc64le/quarterly/ exists and is not empty and is recent.
https://pkg.freebsd.org/ lists FreeBSD:15:powerpc64le (with a URL bound)
https://pkg.freebsd.org/FreeBSD:15:powerpc64le/latest/ exists and is not empty and is recent.

**Comment by dlangille** [comment] 2023-12-07 13:25
The goal: automatically know the list of valid ABI.  I like to do as little as possible.

Compiling that list from a script (`/bin/sh`, `python`, or `perl`) would be helpful.

That script would make a great standalone project.

**Comment by dlangille** [comment] 2023-12-08 15:45
Closing this one. @markmi: thank you.

**Closed by dlangille** 2023-12-08 15:45 UTC
